export enum EnumBelt {
    WHITE = 'WHITE',
    YELLOW = 'YELLOW',
    RED = 'RED',
    ORANGE = 'ORANGE',
    GREEN = 'GREEN',
    PURPLE = 'PURPLE',
    BROWN = 'BROWN',
    BLACK = 'BLACK',
    // BLACK_2 = 'BLACK_2',
    // BLACK_3 = 'BLACK_3',
    // BLACK_4 = 'BLACK_4',
    // BLACK_5 = 'BLACK_5',
    // BLACK_6 = 'BLACK_6',
    // BLACK_7 = 'BLACK_7',
    // BLACK_8 = 'BLACK_8',
    // BLACK_9 = 'BLACK_9',
    // BLACK_10 = 'BLACK_10',
}